# https://docs.gitea.io/en-us/install-with-docker/
# https://docs.drone.io/installation/gitea/multi-machine/
# https://docs.drone.io/administration/agents/linux-amd64/
# https://github.com/drone/drone-yaml-v1/blob/master/samples/5_parallel.yml
version: "3.7"

services:
  gitea:
    image: gitea/gitea:latest
    environment:
      - APP_NAME=Gitea
      - USER_UID=1000
      - USER_GID=1000
      - ROOT_URL=https://gitea.${DOMAIN:-localhost}
      - SSH_DOMAIN=gitea.${DOMAIN:-localhost}
      - SSH_PORT=2222
      - HTTP_PORT=3000
      - DB_TYPE=postgres
      - DB_HOST=gitea-db:5432
      - DB_NAME=gitea
      - DB_USER=postgres
      - DB_PASSWD=postgres
    volumes:
      - gitea_app:/data
    ports:
      - 2222:2222
    networks:
      - public
      - private
    deploy:
      labels:
        - "traefik.docker.network=public"
        - "traefik.port=3000"
        - "traefik.backend=gitea"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:gitea.${DOMAIN:-localhost}"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.entryPoints=http,https"

  gitea-db:
    image: postgres:alpine
    volumes:
      - gitea_db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=gitea
    networks:
      - private

  drone-server:
    image: drone/drone:1.2.1
    volumes:
      - drone:/var/lib/drone
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_DEBUG=true
      - DRONE_ADMIN=rbekker87
      - DRONE_USER_CREATE=username:rbekker87,admin:true
      - DRONE_SERVER_PORT=:80
      - DRONE_DATABASE_DRIVER=sqlite3
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITEA_SERVER=http://gitea:3000
      - DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      - DRONE_SERVER_HOST=drone-server:80
      - DRONE_HOST=http://drone-server:80
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
      - DRONE_AGENTS_ENABLED=true
    networks:
      - public
      - private
    deploy:
      labels:
        - "traefik.docker.network=public"
        - "traefik.port=80"
        - "traefik.backend=drone-server"
        - "traefik.enable=true"
        - "traefik.frontend.rule=Host:drone.${DOMAIN:-localhost}"
        - "traefik.frontend.headers.SSLRedirect=true"
        - "traefik.frontend.entryPoints=http,https"

  drone-agent:
    image: drone/agent:1.2.1
    command: agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DRONE_RPC_SERVER=http://drone-server:80
      - DRONE_RPC_SECRET=9c3921e3e748aff725d2e16ef31fbc42
      - DRONE_RUNNER_CAPACITY=2
    networks:
      - private
    deploy:
      mode: replicated
      replicas: 2

volumes:
  gitea_app: {}
  gitea_db: {}
  drone: {}

networks:
  public:
    external: true
  private:
    external: true
